version: "3.9"
services:
  db:
    image: postgres:9.6.21
    restart: always
    container_name: country-pg
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=countrydb
      - POSTGRES_USER=countryadmin
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgweb:
    image: sosedoff/pgweb:0.11.7
    container_name: country-pgweb
    restart: always
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgres://countryadmin:password@db:5432/countrydb?sslmode=disable
    depends_on:
      - db

  es:
    build: ./es
    container_name: country-es01
    environment:
      - node.name=es01
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
        test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
        interval: 30s
        timeout: 30s
        retries: 3

  web:
    container_name: country-web
    build: .
    environment:
      - SETUP=true
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      es:
        condition: service_healthy

volumes:
  data01:
    driver: local
